# Generated by Django 4.1.5 on 2023-03-30 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("general", "0002_remove_circuit_version"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChampionshipApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Prénom")),
                (
                    "platform",
                    models.CharField(
                        max_length=50,
                        verbose_name="Sur quelle plateforme jouez-vous à F1 ?",
                    ),
                ),
                (
                    "platform_id",
                    models.CharField(
                        max_length=50, verbose_name="Identifiant plateforme"
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("Vendredi", "les vendredis de 20h30 à 22h30"),
                            ("Dimanche", "les dimanches de 20h30 à 22h30"),
                            ("Vendredi et Dimanche", "les vendredis et dimanches"),
                        ],
                        max_length=50,
                        verbose_name="Disponibilités",
                    ),
                ),
                (
                    "teammates",
                    models.CharField(
                        max_length=200, verbose_name="Coéquipiers souhaités"
                    ),
                ),
                (
                    "preferred_team1",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preferred_team1",
                        to="general.team",
                        verbose_name="Ecurie 1 souhaitée",
                    ),
                ),
                (
                    "preferred_team2",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preferred_team2",
                        to="general.team",
                        verbose_name="Ecurie 2 souhaitée",
                    ),
                ),
                (
                    "preferred_team3",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preferred_team3",
                        to="general.team",
                        verbose_name="Ecurie 3 souhaitée",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de championnat",
                "verbose_name_plural": "Demandes de championnat",
            },
        ),
    ]
