# Generated by Django 4.1.5 on 2023-03-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_championshipapplication"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="championshipapplication",
            options={
                "verbose_name": "Inscription championnat",
                "verbose_name_plural": "Inscriptions championnat",
            },
        ),
        migrations.AlterField(
            model_name="championshipapplication",
            name="platform",
            field=models.CharField(max_length=50, verbose_name="Plateforme"),
        ),
    ]
