# Generated by Django 4.1.5 on 2023-03-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_championshipapplication_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="status",
            field=models.CharField(
                choices=[
                    ("Titulaire", "Titulaire"),
                    ("Remplaçant", "Remplaçant"),
                    ("En attente", "En attente"),
                ],
                default="En attente",
                max_length=50,
                verbose_name="Statut licence",
            ),
        ),
    ]
