# Generated by Django 4.2 on 2023-04-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_license_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="license",
            name="license_points",
            field=models.PositiveIntegerField(
                default=16, verbose_name="Points de licence"
            ),
        ),
    ]
