# Generated by Django 4.2 on 2023-04-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_license_license_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="license_points",
            field=models.PositiveIntegerField(
                default=12, verbose_name="Points de licence"
            ),
        ),
    ]
