# Generated by Django 4.2 on 2023-04-05 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_license_license_points"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="license",
            name="license_points",
        ),
    ]
