# Generated by Django 4.2 on 2023-04-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
