# Generated by Django 4.1.5 on 2023-03-29 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("competition", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("points", models.PositiveIntegerField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competition.event",
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.license"
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competition.season",
                    ),
                ),
            ],
            options={
                "verbose_name": "Résultat course",
                "verbose_name_plural": "Résultats course",
            },
        ),
        migrations.CreateModel(
            name="ClaimRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("Qualifications", "Qualifications"),
                            ("Course", "Course"),
                        ],
                        max_length=50,
                        verbose_name="Type de session",
                    ),
                ),
                (
                    "lap_number",
                    models.PositiveIntegerField(verbose_name="Tour de l'incident"),
                ),
                (
                    "incident_description",
                    models.TextField(verbose_name="Description de l'incident"),
                ),
                ("video_url", models.URLField(verbose_name="URL de la vidéo")),
                (
                    "video_timestamp",
                    models.CharField(
                        max_length=15, verbose_name="Timecode de l'incident"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event_registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competition.eventregistration",
                        verbose_name="Participant réclamé",
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.license",
                        verbose_name="Licence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réclamation championnat",
                "verbose_name_plural": "Réclamations championnat",
            },
        ),
    ]
