# Generated by Django 4.1.5 on 2023-03-30 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("competition", "0002_alter_season_options_alter_event_season_and_more"),
        ("users", "0001_initial"),
        ("bureaufia", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventresult",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="competition.event",
                verbose_name="Evénement",
            ),
        ),
        migrations.AlterField(
            model_name="eventresult",
            name="license",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.license",
                verbose_name="Licence",
            ),
        ),
        migrations.AlterField(
            model_name="eventresult",
            name="points",
            field=models.PositiveIntegerField(verbose_name="Points"),
        ),
        migrations.AlterField(
            model_name="eventresult",
            name="position",
            field=models.PositiveIntegerField(verbose_name="Position"),
        ),
        migrations.AlterField(
            model_name="eventresult",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="competition.season",
                verbose_name="Saison",
            ),
        ),
    ]
