# Generated by Django 4.1.5 on 2023-03-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bureaufia",
            "0002_alter_eventresult_event_alter_eventresult_license_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="claimregistration",
            name="admin_response",
            field=models.TextField(
                blank=True, null=True, verbose_name="Réponse de l'administrateur"
            ),
        ),
        migrations.AddField(
            model_name="claimregistration",
            name="is_resolved",
            field=models.BooleanField(
                default=False, verbose_name="Réclamation traitée"
            ),
        ),
    ]
