# Generated by Django 4.2 on 2023-04-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bureaufia", "0003_claimregistration_admin_response_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventresult",
            name="best_lap",
            field=models.BooleanField(
                default=False, verbose_name="Meilleur tour en course"
            ),
        ),
    ]
