# Generated by Django 4.2 on 2023-05-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0002_game_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
