# Generated by Django 4.1.5 on 2023-03-29 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("general", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_date", models.DateTimeField(verbose_name="Date de la course")),
                (
                    "circuit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="general.circuit",
                        verbose_name="Circuit",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="general.game",
                        verbose_name="Nom du jeu",
                    ),
                ),
                (
                    "league",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="general.league",
                        verbose_name="Ligue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course championnat",
                "verbose_name_plural": "Courses championnats",
                "ordering": ["event_date"],
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="SpecialEventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_registered",
                    models.CharField(
                        choices=[
                            ("Absent", "Absent"),
                            ("Présent", "Présent"),
                            ("Remplaçant", "Remplaçant"),
                        ],
                        default="En attente",
                        max_length=50,
                        verbose_name="S'est enregistré",
                    ),
                ),
                (
                    "registration_date",
                    models.DateTimeField(
                        null=True, verbose_name="Date de l'inscription"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competition.event",
                        verbose_name="Evénement",
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.license",
                        verbose_name="Licence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription événement spécial",
                "verbose_name_plural": "Inscriptions événements spéciaux",
            },
        ),
        migrations.CreateModel(
            name="SpecialEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_date", models.DateTimeField(verbose_name="Date de la course")),
                (
                    "circuit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="general.circuit",
                        verbose_name="Circuit",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="general.game",
                        verbose_name="Nom du jeu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evénement spécial",
                "verbose_name_plural": "Evénements spéciaux",
                "ordering": ["event_date"],
            },
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_registered",
                    models.CharField(
                        choices=[
                            ("Absent", "Absent"),
                            ("Présent", "Présent"),
                            ("Remplaçant", "Remplaçant"),
                        ],
                        default="En attente",
                        max_length=50,
                        verbose_name="S'est enregistré",
                    ),
                ),
                (
                    "registration_date",
                    models.DateTimeField(
                        null=True, verbose_name="Date de l'inscription"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competition.event",
                        verbose_name="Evénement",
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.license",
                        verbose_name="Licence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription championnat",
                "verbose_name_plural": "Inscriptions championnats",
            },
        ),
        migrations.AddField(
            model_name="event",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="competition.season"
            ),
        ),
    ]
