# Generated by Django 4.2 on 2023-05-19 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("general", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_date", models.DateTimeField(verbose_name="Date de la course")),
                (
                    "circuit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="general.circuit",
                        verbose_name="Circuit",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="general.game",
                        verbose_name="Nom du jeu",
                    ),
                ),
                (
                    "league",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="general.league",
                        verbose_name="Ligue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course championnat",
                "verbose_name_plural": "Courses championnats",
                "ordering": ["event_date"],
            },
        ),
        migrations.CreateModel(
            name="WeekEndFormat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nom du format")),
            ],
            options={
                "verbose_name": "Format de week-end",
                "verbose_name_plural": "Formats de week-end",
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom saison")),
                ("start_date", models.DateField(verbose_name="Date début")),
                (
                    "game",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="general.game",
                        verbose_name="Nom du jeu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saison",
                "verbose_name_plural": "Saisons",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_registered",
                    models.CharField(
                        choices=[
                            ("Absent", "Absent"),
                            ("Présent", "Présent"),
                            ("Remplaçant", "Remplaçant"),
                        ],
                        default="En attente",
                        max_length=50,
                        verbose_name="S'est enregistré",
                    ),
                ),
                (
                    "registration_date",
                    models.DateTimeField(
                        null=True, verbose_name="Date de l'inscription"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competition.event",
                        verbose_name="Evénement",
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.license",
                        verbose_name="Licence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription course",
                "verbose_name_plural": "Inscriptions course",
            },
        ),
        migrations.CreateModel(
            name="EventPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="competition.event",
                    ),
                ),
                ("name", models.ManyToManyField(to="competition.weekendformat")),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="competition.season",
                verbose_name="Saison",
            ),
        ),
        migrations.CreateModel(
            name="ScoringRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(verbose_name="Position")),
                ("points", models.PositiveIntegerField(verbose_name="Points")),
                (
                    "event_part",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competition.eventpart",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="general.game",
                        verbose_name="Jeu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Règle calcul de points",
                "verbose_name_plural": "Règles calcul de points",
                "ordering": ["game", "event_part", "position"],
                "unique_together": {("game", "event_part", "position")},
            },
        ),
    ]
