# Generated by Django 4.2 on 2023-05-22 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0002_game_slug"),
        ("users", "0002_remove_license_total_points"),
        ("competition", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scoringrule",
            options={
                "ordering": ["season", "weekend_format", "position"],
                "verbose_name": "Règle de calcul de points",
                "verbose_name_plural": "Règles de calcul de points",
            },
        ),
        migrations.AlterUniqueTogether(
            name="scoringrule",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="event",
            name="weekend_format",
            field=models.ManyToManyField(
                to="competition.weekendformat", verbose_name="Format du week-end"
            ),
        ),
        migrations.AddField(
            model_name="scoringrule",
            name="best_lap",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Points pour meilleur tour"
            ),
        ),
        migrations.AddField(
            model_name="scoringrule",
            name="season",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="competition.season",
                verbose_name="Saison",
            ),
        ),
        migrations.AddField(
            model_name="scoringrule",
            name="weekend_format",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="competition.weekendformat",
                verbose_name="Epreuve",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="league",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="general.league",
                verbose_name="Ligue",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="scoringrule",
            unique_together={("season", "weekend_format", "position")},
        ),
        migrations.CreateModel(
            name="EventResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(null=True, verbose_name="Position"),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        blank=True, default=0, editable=False, verbose_name="Points"
                    ),
                ),
                (
                    "best_lap",
                    models.BooleanField(
                        default=False, verbose_name="Meilleur tour en course"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competition.event",
                        verbose_name="Événement",
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.license",
                        verbose_name="Licence",
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competition.weekendformat",
                        verbose_name="Épreuve",
                    ),
                ),
            ],
            options={
                "verbose_name": "Résultat événement",
                "verbose_name_plural": "Résultats événement",
                "unique_together": {("event", "phase", "license")},
            },
        ),
        migrations.RemoveField(
            model_name="scoringrule",
            name="event_part",
        ),
        migrations.RemoveField(
            model_name="scoringrule",
            name="game",
        ),
        migrations.DeleteModel(
            name="EventPart",
        ),
    ]
