# Generated by Django 4.1.5 on 2023-03-30 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("competition", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="season",
            options={
                "ordering": ["-start_date"],
                "verbose_name": "Saison",
                "verbose_name_plural": "Saisons",
            },
        ),
        migrations.AlterField(
            model_name="event",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="competition.season",
                verbose_name="Saison",
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="end_date",
            field=models.DateField(verbose_name="Date fin"),
        ),
        migrations.AlterField(
            model_name="season",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nom saison"),
        ),
        migrations.AlterField(
            model_name="season",
            name="start_date",
            field=models.DateField(verbose_name="Date début"),
        ),
    ]
