# Generated by Django 4.1.5 on 2023-03-30 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("competition", "0002_alter_season_options_alter_event_season_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specialeventregistration",
            name="event",
        ),
        migrations.RemoveField(
            model_name="specialeventregistration",
            name="license",
        ),
        migrations.AlterModelOptions(
            name="eventregistration",
            options={
                "verbose_name": "Inscription course",
                "verbose_name_plural": "Inscriptions course",
            },
        ),
        migrations.DeleteModel(
            name="SpecialEvent",
        ),
        migrations.DeleteModel(
            name="SpecialEventRegistration",
        ),
    ]
