# Generated by Django 4.2 on 2023-04-06 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("competition", "0003_remove_specialeventregistration_event_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="season",
            name="end_date",
        ),
    ]
