# Generated by Django 4.2 on 2023-04-06 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0003_delete_platform"),
        ("competition", "0004_remove_season_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="game",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="general.game",
                verbose_name="Nom du jeu",
            ),
        ),
    ]
